name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          npm version patch -m "Release version %s"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags

      - name: Build package
        run: npm run build

      - name: Deploy to release branch
        run: |
          git checkout -b release
          git push origin release --force
